- src/core/lens_profile.rs
- src/core/lib.rs
added some #[feature] gates, removing calibrator if opencv is not enabled
> support building gyroflow-core without opencv

- src/ui/App.qml
- src/ui/main_window.qml
Fix for issue where clicking twice on the windows close button would bypass the close confirmation. 
Allow closing the app without confirmation when nothing was loaded.
> Improved close confirmation triggering

- src/core/gyro_source.rs
Unified structure of quat_at_timestamp & offset_at_timestamp functions, as they do roughly the same thing.
Added a fast bypass in case the first lookup found the exact timestamp. In this case no second lookup is required.
> At timestamp optimization

- src/core/lib.rs
I've sorted mutex acquisitions in the same order. So far I've only seen this deadlock, but with the number of mutexes used in this struct we need to rethink the approach at some point.
> Fix a deadlock when loading `.gyroflow` file (#55)

- src/rendering/ffmpeg_processor.rs
The thread count is set fixed to 3, which gives about 20% performance increase. Anything more doesn't actually improve anything.
> Enable ffmpeg threads when decoding

- src/controller.rs
- src/core/lib.rs
- `recompute_undistortion` was called twice for size changes, in `StabilizationManager::get_render_stabilizator`
- don't `request_recompute` when setting a size but it isn't actually different.
> Reduce size recompute, when nothing changed

- src/rendering/ffmpeg_video.rs
This is just for seeking in players and performance in multithreaded decoders. Inserts regular keyframes in 1sec steps.
> Set encoder GOP to approx 1sec

- .vscode/launch.json
- .vscode/tasks.json
- src/rendering/ffmpeg_audio.rs
When decoder is `PCM` then the bit rate is way to high for the `AAC` encoder.
This limits it to `320kbps` and stops the codec from complaining.
> Limit audio bitrate

- src/ui/components/LoaderOverlay.qml
The busy indicators were always running in the background (just with 0 opacity), this stops them and completely zeroes out the idle CPU & GPU usage.
> Zero idle CPU/GPU usage

- src/ui/components/Label.qml
- src/ui/components/NumberField.qml
- src/ui/components/SliderWithField.qml
- src/ui/menu/Export.qml
- src/ui/menu/Synchronization.qml
Add faster shortcut for reset brought up here: https://github.com/gyroflow/gyroflow/issues/189
Values of sliders and numberfields can be reset through the context menu, ctrl+click or reset button (only enabled when value isn't default):
> Add value reset shortcut

- src/core/zooming/fov_default.rs
- src/core/zooming/fov_direct.rs
- src/core/zooming/mod.rs
- src/core/zooming/zoom_dynamic.rs
- src/core/zooming/zoom_static.rs
Added new `direct` FOV estimator. It's about twice as fast by not using atan2 like the `default` one.
On my tests, the error between the `direct` and the `default` is less than 0.1% for a GoPro lens. It should be carefully tested with more extrem lens distortions.
> Added direct FOV estimator and set it to be used by the zooming algo

- src/core/zooming/fov_iterative.rs
- src/core/zooming/mod.rs
This one doesn't interpolate between the polygon points directly, it calls `undistort_points` multiple times with more fine grained edge points. It should be in theory more accurate than the previous version. It might fail if the initial polygon was way too inaccurate. However the other FOV estimators have a similar problem.
> New iterative FOV estimator

- src/core/synchronization/akaze.rs
- src/core/synchronization/autosync.rs
- src/core/synchronization/mod.rs
- src/core/synchronization/opencv.rs
Precache Optical Flow data during auto sync process, so it isn't required to run it during playback and basically any screen-refresh.
> Precache Optical Flow during auto sync

- src/ui/components/Label.qml
- src/ui/components/NumberField.qml
- src/ui/menu/Export.qml
- src/ui/menu/LensProfile.qml
- src/ui/menu/VideoInformation.qml
- Removed a lot of similar width/height properties, not sure why they were needed in the first place.
- Added possibility to add a custom `reset` function to `NumberField`
- Reset size to initial values when using double click & context menu reset
- Reset Bitrate to source bitrate on reset (instead of fixed 20MBit/s)
> Cleanup size input code in export settings

- src/core/undistortion/cpu_undistort.rs
Limit how much the undistortion approximation can move during each iteration. Might require some tweaking of loop iteration count & `t_max_fix` later on
> Limit undistort approximation movements

- src/ui_live_reload.cpp
previousItem is already deleted by the previous if statement by deleting an item having the same object name "App".
> Fixed a bug which caused crashes in runtime.

- src/resources.rs
- src/ui/App.qml
- src/ui/Calibrator.qml
- src/ui/Shortcuts.qml
- src/ui/VideoArea.qml
- src/ui/components/Timeline.qml
- replaced key presses with shortcuts
- moved all shortcuts into separate file
- fixed issue where `space` key press in calibrator would trigger play/pause in main window
- fixed issue where clicking `trim start button` and `trim end button` on the same frame would create an empty trim section
- added shortcut `,`, `.`,`Ctrl+,`, `Ctrl.` for prev/next frames
- added shortcut `i`, `o` for set trim start/end
- added shortcut `m` for mute/un-mute
- added shortcut `s` for stabilization enable/disable
> Extended keyboard shortcuts

- src/ui/components/TimelineRangeIndicator.qml
When dragging trim start/end handles very slowly, there is a glitch at the very beginning of the dragging where the end point would jump around. This was caused by `onCentroidChanged` being triggered before `activeTranslation` updated.
> Fix for trim start/end glitching at beginning of drag

- src/core/gyro_source.rs
- src/core/smoothing/horizon.rs
Implement https://github.com/gyroflow/gyroflow/issues/24
Notes:
* Although Hero 8 contain the GRAV metadata, it's unfortunately blank, so this only works for hero 9 and newer.
* Gravity vector is given in the body coordinate system, so using it consists of extracting the roll component and correcting for the roll difference between original and smoothed orientations. It seems to work, but math is a bit wonky, so there might be a mistake somewhere.
> Use gravity vector for horizon lock

- src/core/gyro_source.rs
- src/core/integration.rs
This might not be 100% correct, but it appears to be working fine.
To not interfer with gravity vectors, the quaternion correction is only applied if they aren't present. Ideally, the gravity vector horizon lock would take this correction into account, as it makes the GoPro quaternions orient in the same way as they are after the other integration methods.
> Initial horizon lock fix for Hero8

- Cargo.lock
- Cargo.toml
- src/ui/App.qml
- src/ui/Calibrator.qml
- src/ui/RenderQueue.qml
- src/ui/VideoArea.qml
- src/ui/components/Action.qml
- src/ui/components/Button.qml
- src/ui/components/LinkButton.qml
- src/ui/components/Menu.qml
- src/ui/components/MenuItem.qml
- src/ui/components/Modal.qml
- src/ui/components/NumberField.qml
- src/ui/components/Popup.qml
- src/ui/components/SliderWithField.qml
- src/ui/components/SplitButton.qml
- src/ui/components/TableList.qml
- src/ui/components/Timeline.qml
- src/ui/components/TimelineSyncPoint.qml
- src/ui/menu/Advanced.qml
- src/ui/menu/Export.qml
- src/ui/menu/LensCalibrate.qml
- src/ui/menu/LensProfile.qml
- src/ui/menu/MotionData.qml
- src/ui/menu/Stabilization.qml
- src/ui/menu/Synchronization.qml
- src/ui/menu/VideoInformation.qml
Add backup icon.source in case theme fails to load
https://doc.qt.io/qt-6/qtquickcontrols2-icons.html
"Both icon.name and icon.source can be set to ensure that an icon will always be found. If the icon is found in the theme, it will always be used; even if icon.source is also set."
Update qml-video-rs version to allow build - see:
https://github.com/AdrianEddy/qml-video-rs/pull/2
On opensuse tumbleweed:
> #134 - Bug Fix: Icons missing in Linux

- src/core/keyframes.rs
- src/ui/Shortcuts.qml
- src/ui/components/Timeline.qml
- src/ui/components/TimelineKeyframesView.rs
Added helper functions for retrieving keyframes before or after a timestamp
- can be used for only one specific keyframe type or all types at once
- added keyboard shortcuts `Shift+Left` & `Shift+Right` to navigate through the keyframes in the timeline
> Timeline keyframe navigation shortcuts

- src/ui/components/NumberField.qml
- src/ui/components/SliderWithField.qml
The context menu of number fields adjacent to sliders wasn't showing "Enable Keyframes" as available, because the number fields itself have the keyframe property not set. 
With this change we just use the same context menu for the number field, as we have for the slider.
> Use slider context menu for adjacent number field

- src/ui/components/Timeline.qml
When editing a sync point and then triggering "Delete all sync points" from the timeline, now closes the editing process
> Stop editing sync points, when deleting all of them

- src/controller.rs
- src/ui/VideoArea.qml
When keyframes getting changed in timeline (delete / ease), update the controls in the sidepanel.
> Update controls for keyframe changes in timeline

- src/core/gyro_source.rs
- src/core/smoothing/horizon.rs
In `recompute_smoothness` you can switch between the original order and the new one for now
> Horizon-Lock before smoothing

- src/core/stabilization/frame_transform.rs
Rolling shutter was acting incorrectly when there was a significant roll difference between original and smoothed orientations (see attached clip), indicating the smoothed orientation was incorrectly applied somewhere. Swapping the rotation order in the quaternion multiplication seems to have fixed this (smoothed_quat now applied last instead of first in the sequence)
https://user-images.githubusercontent.com/20195216/185305280-039b41fa-fa11-4c7c-8b5f-e3ab5f4a390f.mp4
https://user-images.githubusercontent.com/20195216/185304995-3c1ccc11-a00e-4414-8ee9-c2ffd2666df8.mp4
> Fix rolling shutter bug

- src/ui/menu/Stabilization.qml
Fix https://github.com/gyroflow/gyroflow/issues/439
> Fix default lens correction strength after reset

- src/controller.rs
- src/core/Cargo.toml
- src/core/synchronization/mod.rs
- src/core/synchronization/optimsync.rs
- src/ui/menu/Synchronization.qml
The idea is pretty simple. We look at the gyro spectrum and give higher rank to segments which contain more middle frequencies (2-30 hz) and less low (<2 hz) and high (>30 hz) frequencies. Then we run thresholding and non-maximum suppression with a radius of 8 seconds. Then, we randomly select the required number of points from candidates.
But please test this a bit more before release
> Experimental auto sync point selection

- _deployment/mac/Gyroflow.app/Contents/Info.plist
- Updated `Info.plist`, and changed from `Alternate` rank to `None` and `Editor` role to `Viewer`.
- As discussed on Discord.
> Prevent Gyroflow from being default media player

- src/ui/components/Timeline.qml
I changed the behaviour of the timeline scrolling on MacOS so the movement is more coherent with natural scroll we are used to. 
Managed to change the tooltip so no translation needs to be changed, but the text ends up like _"Scroll to zoom horizontally, Option+Scroll to zoom vertically, Scroll to pan, double click to reset zoom"_
Please check vertical zooming on windows, I did not understand why `wheel.angleDelta.x` is used there, but I kept like it was.
> Natural timeline scrolling on MacOS

- src/rendering/render_queue.rs
- src/ui/RenderQueue.qml
I propose these changes to fix an issue with fps and time remaining estimation in the render queue. 
The problem appears when:
- Add items to the queue, start it and wait all items finished rendering
- wait a little bit (the more you wait, the more the values derives)
- Add new items, start the queue again
Then you'll see fps and time remaining estimation wrong, as they are computed from the time the queue was started first. 
I am naively proposing these changes, looks like it fixes the issue. I decided to run the `start()` function each time a job is finished, as the `start` function does the job of ending queue if no jobs left. Thing is I don't call `update_status()` anymore, I don't know what it was useful for, but I guess `start()` could do the same thing if needed.
> Fix queue progress

- src/ui/App.qml
Takes the default overwrite action from the queue settings and use it on the "Add to render queue button"
Also added user feedback after adding to the queue by showing a message and disabling the button for 2 secs
> Add to queue behaviour

- src/core/stabilization/cpu_undistort.rs
- src/core/stabilization/frame_transform.rs
- src/core/synchronization/find_offset/visual_features.rs
- src/core/zooming/fov_iterative.rs
Added a use_fovs parameter to the at_timstamp_for_points method so that it can be exposed by undistort_points_with_rolling_shutter. All current calls will pass false to preserve existing functionality. External users of the core library can now undistort points correctly wrt fov settings in the ComputeParams.
> Allow undistort with fov

- src/ui/components/Timeline.qml
This enables timeline scrolling using horizontal mouse wheel for non-MacOS platforms (there was already code for that).
Tested on Windows using a mouse with a horizontal wheel and with a laptop touchpad.
> Enable scrolling using horizontal wheel

- src/ui/components/NumberField.qml
This enables overwrite mode toggling using Insert key for number fields. It should make it easier to adjust values during keyframing (no need to make text selections to replace or use Delete/Backspace keys in this mode).
Tested on Windows. One issue I found is that in replace mode, if an invalid character is typed, input validator stops it from appearing in the input field, but the previous character at the cursor position is erased anyway. I didn't find an easy way to prevent it from happening.
> Enable overwrite mode using Insert key

- _scripts/common.just
- _scripts/linux.just
This PR changes the Just files to detect whether `apt-get` is present on the user's system. If not, `apt-get install` commands are skipped and a warning is presented to the user that they are responsible for installing required libraries.
Additionally, this PR makes the check for `LIBCLANG_PATH` more robust.
Sidenote: it seems that if `libclang` is not present on the system, libclang-13 is attempted to be installed. However, the lowest version of libclang that I could get to work was `libclang-15`. Should the `-13` version be bumped?
> Make linux build more tolerant of non-debian systems

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Gyroflow Guru](https://gurubase.io/g/gyroflow) to Gurubase. Gyroflow Guru uses the data from this repo and data from the [docs](https://docs.gyroflow.xyz) to answer questions by leveraging the LLM.
In this PR, I showcased the "Gyroflow Guru", which highlights that Gyroflow now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you …
> Introducing Gyroflow Guru on Gurubase.io

- src/ui/VideoArea.qml
- Support the old GoPro file name convention as used from GoPro 1 through 5 with a GOPRO[id] as first, followed by GOPRO[seq][id].
- Detect the split sequence and offer to merge also when opening any intermediate chapter in GoPro sequences.
Instead of fetching the start index from the filename, for gopro files we give directly what the first index should be and start probing from there. This allows us to switch to the different prefix form of the old GoPro 1-5 file names (see https://community.gopro.com/s/article/GoPro-Camera-File-Naming-Convention?language=en_US) easily, as well as detecting a split sequence by opening any chapter from it which is very convenient.
I have no experience with the DJI filenames and the documentation online wasn't 100% clear, but the detector seems to …
> Improve split sequence detection for GoPro 1-5

- src/controller.rs
- src/core/lib.rs
- src/core/synchronization/optimsync.rs
- src/rendering/render_queue.rs
1.the rank is generally less than 6 when static,and more than 15 when handheld.So 13.0 would be better. 
2.trim ranges should minus initial_offset to convert to gyro data ranges.
> improve "get optimsync point"
