src/ui/menu/Synchronization.qml
src/ui/menu/VideoInformation.qml

Fix https://github.com/gyroflow/gyroflow/issues/59

Fix initial video orientation

---

src/ui/VideoArea.qml
src/ui/components/Timeline.qml

This fixes an issue where clicking in the timeline would make the playhead jump back and forth.

Smoother timeline seeks

---

README.md

This is just one line fix, I'll cancel the CI run.

Add side note for building on windows

---

src/ui/components/Button.qml
src/ui/components/CheckBox.qml
src/ui/components/ComboBox.qml
src/ui/components/LinkButton.qml
src/ui/components/MenuItem.qml
src/ui/components/Popup.qml
src/ui/components/TableList.qml
src/ui/components/TimelineAxisButton.qml

Implement https://github.com/gyroflow/gyroflow/issues/29 for current UI elements

Add activeFocus indicators and keyboard control

---

src/core/smoothing/fixed.rs
src/core/smoothing/horizon.rs
src/core/smoothing/mod.rs
src/core/smoothing/none.rs
src/core/smoothing/plain.rs
src/core/smoothing/velocity_dampened.rs
src/core/smoothing/velocity_dampened_axis.rs
src/core/smoothing/velocity_dampened_v1.rs
src/ui/menu/Stabilization.qml

Implements https://github.com/gyroflow/gyroflow/issues/14

Horizon lock as checkbox for all smoothing methods

---

src/core/smoothing/mod.rs
src/core/smoothing/velocity_dampened.rs
src/core/smoothing/velocity_dampened_advanced.rs
src/core/smoothing/velocity_dampened_axis.rs

Velocity dampened:
- hardcoded 500 deg/s max velocity for consistent results between videos and different trim zones
- smoothness sliders removed
- hardcoded smoothness values 1s and 0.1s
Velocity dampened (Advanced):
- just hardcoded 500 deg/s max velocity
- smoothness sliders kept

Intuitive Velocity dampened slider

---

src/core/smoothing/default_algo.rs
src/core/smoothing/mod.rs

Has the functionality of Velocity dampened and Velocity dampened per axis combined

Added Default smoothing algorithm

---

README.md
src/ui/menu/MotionData.qml

To go with https://github.com/AdrianEddy/telemetry-parser/pull/14
I'm not sure if we also need to update the git hash in the Cargo stuff once the telemetry-parer PR is merged?

Add log as motion data file type

---

Cargo.toml
README.md

Added cargo profile for profiling.
Added "Profiling on Windows" to the readme

Added profile for profiler

---

README.md

Just a small thing we missed for days..
Maybe this mention is too small or there's better approach, so please review this. @AdrianEddy @ilya-epifanov @ElvinC

Add OpenFX info in readme

---

src/core/lens_profile.rs
src/core/lib.rs
src/core/zooming/adaptive.rs
src/core/zooming/mod.rs

Moved AdaptiveZoom into a new directory for different types of zooming algorithms.
Added a simple Factory for different zoom types.

Directory structure for different Zooming Algorithms

---

.vscode/launch.json
.vscode/tasks.json

- Build tasks for "Tasks: Run Build Task" menu (Ctrl+Shift+B by default)
- Added debug configuration for `build & run` or just `run`

Added build tasks for VSCode

---

src/core/zooming/fov_direct.rs

This addresses issues with extreme lens distortions (like Go2) on the `FovDirect` estimator.

Fix for extreme distortions in FovDirect implementation

---

src/core/gpu/opencl_undistort.cl
src/core/gpu/wgpu_undistort.wgsl
src/core/undistortion/cpu_undistort.rs

Minor undistortion optimization

---

src/ui/App.qml
src/ui/Calibrator.qml
src/ui/components/MenuItem.qml

- Added menu separation lines
- Removed Hover/down effect from menu titles (looked stupid with the added lines)
- Added padding to the bottom of menus

Menu separation

---

src/ui/menu/Export.qml

- added button next to the output size settings
- added popup menu with common video formats

Very basic video-sizes menu

---

src/ui/App.qml
src/ui/components/Button.qml
src/ui/components/CheckBox.qml
src/ui/components/ComboBox.qml
src/ui/components/MenuItem.qml
src/ui/components/NumberField.qml
src/ui/components/Popup.qml
src/ui/components/Timeline.qml
src/ui/components/TimelineAxisButton.qml

No idea why it was implemented as key press instead of a shortcut. But this appears to work.

Window wide spacebar shortcut

---

src/ui/App.qml

Don't scroll the line between `Logo` & `Video Information` with the side panel

Don't scroll log separator line

---

src/ui/Shortcuts.qml
src/ui/components/Timeline.qml

- added `x`, `y`, `z`, `w` keyboard shortcuts to toggle chart axis
- combined with `Shift` key it'll hide all other axis

Added keyboard shortcuts for axis buttons

---

src/ui/components/SearchField.qml

This way searching for eg. `insta go` works as expected

Multi word search instead of fulltext

---

src/rendering/ffmpeg_audio.rs

- Some files don't have channel layout information, so set the channel layout using channels
- addresses #287

Multichannel audio fix

---

src/core/lib.rs

fixed compilation without opencv

---

src/core/smoothing/horizon.rs

Simplified for readability
Compared with the original code, the resulting quaternions never differ more than 1e-10rad in angle

Refactored lock_horizon_angle function

---

src/ui/Shortcuts.qml
src/ui/components/Timeline.qml

`shift` + `g` / `a` / `m` / `q`

Added keyboard shortcuts for chart modes

---

src/ui/Shortcuts.qml
src/ui/components/Timeline.qml

`a` Auto sync here
`p` Add manual sync point here

Added keyboard shortcuts for auto/manual sync points

---

src/core/gyro_source.rs
src/core/imu_integration/mod.rs
src/core/lib.rs

Use VQF to correct CORI data on hero8

---

LICENSE
README.md

- Added an additional permission under section 7 of the GPLv3 to allow App Store usage.
- Added BRAW Toolbox to notable contributors section of README.

Added additional GPLv3 Permission

---

Cargo.lock
Cargo.toml
Justfile
_scripts/linux.just
_scripts/macos.just
_scripts/windows.just
src/ui/components/NumberField.qml
src/ui/ui_tools.rs

This changes the behavior of up and down keys in Numeric Fields to work in a similar fashion to DaVinci Resolve. The digit under the cursor position is incremented.
Not sure about `UtilTest.js`, I felt I needed to have the function covered by a test, but I didn't find a good place to put it...

Increment values in number field using up/down keys based on cursor position

---

src/ui/components/SliderWithField.qml

If a project file contains keyframes, enable it in the appropriate fields

Enable keyframes on project file load

---

src/rendering/ffmpeg_processor.rs

Hi,
love gyroflow and never had any problem using it.
However, since I moved from Windows to Mac, DaVinci has not been able to read timecode from my Sony cameras. I'm using gyroflow with `Preserve other tracks`
This is weird, but following advice on [StackOverflow](https://video.stackexchange.com/questions/17948/ffmpeg-preserve-timecode-when-converting-mp4-to-mov), I was able to manually have ffmpeg create a MOV that DaVinci recognizes.
This PR basically does the same as ffmpeg's `-map_metadata 0:s:2`.
`ffprobe` seems to be happier too:
```
$ ffprobe unpatched.mov
[...]
Stream #0:0[0x1]: Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt2020nc/bt2020/unknown, progressive), 3840x2160, 101633 kb/s, SAR 1:1 DAR 16:9, 24.54 fps, 25 tbr, 25k tbn (default)
Metadata:
creation_time   : …
```

Copy Sony rtmd metadata to global metadata

---

_scripts/linux.just

Revert "fix link for appimagetool for support non-glibc systems"
